/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui;

import Business.DTO.StaffDTO;
import Business.Sevice.StaffSevice;
import DAL.Entity.Staff;
import Utils.BoxDiaglog;
import Utils.ServerHelper;
import java.awt.Color;
import java.util.List;

/**
 *
 * @author pc
 */
public class Login extends javax.swing.JFrame {
    
 
    StaffSevice sev;

    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        sev = new StaffSevice();
        
        
    }

    Login(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtPassw = new javax.swing.JPasswordField();
        txtUrser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblForgetPass = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnDangky = new javax.swing.JButton();
        chkHienmatkhau = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(74, 31, 61));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(186, 79, 84));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassw.setBackground(new java.awt.Color(186, 79, 84));
        txtPassw.setText("Password");
        txtPassw.setBorder(null);
        jPanel3.add(txtPassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 200, 30));

        txtUrser.setBackground(new java.awt.Color(186, 79, 84));
        txtUrser.setText("UserName");
        txtUrser.setBorder(null);
        txtUrser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUrserActionPerformed(evt);
            }
        });
        jPanel3.add(txtUrser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 200, 30));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 210, 10));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 210, 10));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/locks.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 20, 30));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/users.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 20, 30));

        lblForgetPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblForgetPass.setForeground(new java.awt.Color(204, 204, 204));
        lblForgetPass.setText("Forget Password?");
        jPanel3.add(lblForgetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 0, 20, -1));

        btnLogin.setBackground(new java.awt.Color(186, 79, 84));
        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLogin.setText("Sign In");
        btnLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 100, 30));

        btnDangky.setBackground(new java.awt.Color(186, 79, 84));
        btnDangky.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDangky.setText("Sign Up");
        btnDangky.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(btnDangky, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 90, 30));

        chkHienmatkhau.setText("Hiện mật khẩu");
        jPanel3.add(chkHienmatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        txtUrser.setBackground(Color.white);
        txtPassw.setBackground(Color.white);
        if (txtUrser.getText().trim().length() > 0) {
            if (txtPassw.getPassword().length > 0) {
                login();
            } else {
                txtPassw.setBackground(Color.pink);
                BoxDiaglog.alert(this, "Mật khẩu không đúng");
            }
        } else {
            txtUrser.setBackground(Color.pink);
            BoxDiaglog.alert(this, "Bạn không được để trống tài khoản?");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if (BoxDiaglog.Confirm(this, "Bạn muốn thoát hay không?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void txtUrserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUrserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUrserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangky;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chkHienmatkhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblForgetPass;
    private javax.swing.JPasswordField txtPassw;
    private javax.swing.JTextField txtUrser;
    // End of variables declaration//GEN-END:variables

    private void login() {
        List <StaffDTO> listStaff = sev.getAll();
        String manv = txtUrser.getText();
        String passw = new String(txtPassw.getPassword());
        
        
        for(int i =0; i<listStaff.size()+1; i++){
            if(i<listStaff.size()){
                if(listStaff.get(i).getTaiKhoan().equals(manv) &&
                   listStaff.get(i).getMatKhau().equals(passw)){
                 BoxDiaglog.alert(this, "Bạn đăng nhập thành công");
                 
                 return;
                }
            }
            BoxDiaglog.alert(this, "Bạn đăng nhập thất bại");
        }
        }
        
//        try {
//            Staff nv = new Staff();
//            if (nv != null) {
//                
//                String checkPass = nv.getMatKhau();
//                if (passw.equals(checkPass)) {
//                 
//                    ServerHelper.URSER = nv;
//                    BoxDiaglog.alert(this, "Bạn đăng nhập thành công");
//                    this.dispose();
//                } else {
//                    BoxDiaglog.alert(this, "Mật khẩu không đúng?");
//                }
//            } else {
//                BoxDiaglog.alert(this, "Sai tài khoản đăng nhập?");
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//            BoxDiaglog.alert(this, "Lỗi truy vấn dữ liệu");
//        }
        
    }
        

